### ISSUE TITLE
Add support for Realtek RTL8723DE 802.11b/g/n

### ISSUE THREAD

**Issue by ShadowOfPripyat** [EDLLT/WSL2-Linux-Kernel#5]
Hello. I wanted to get this kernel working on my WSL2, and i didn't find compatibility with my WiFi card. I've seen that there's already similar cards of the RTL8723 series, but the one I have is _missing_
![image](https://user-images.githubusercontent.com/73404930/189531674-a1dd997a-d41d-4055-ba5a-9bde21bb25f4.png)
i upload these images in case is useful
![image](https://user-images.githubusercontent.com/73404930/189531793-d4e4374d-2b18-432a-9065-6550d8ec3149.png)

**Comment by EDLLT** [comment]
In order to find the driver you need, all what you have to do is search "driver name GitHub" in google, and then find the appropriate driver which is usually the first result

Here's the driver
https://github.com/smlinux/rtl8723de
Download this driver as a zip, extract it and then follow the steps from https://github.com/EDLLT/WSL2-Linux-Kernel#how-do-i-add-a-wireless-adapter-driver-and-enable-it
